import pojo.TaiKhoan;

public class ChucNangSinhVien extends javax.swing.JFrame {
    
    private final TaiKhoan taiKhoan;
    /**
     * Creates new form ChucNangSinhVien
     * @param taiKhoan
     */
    public ChucNangSinhVien(TaiKhoan taiKhoan) {
        this.taiKhoan = taiKhoan;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSinhVien = new javax.swing.JLabel();
        btnSVDKHP = new javax.swing.JButton();
        btnSVKQDKHP = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnSVTTTK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbSinhVien.setText("SINH VIÊN");

        btnSVDKHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSVDKHP.setText("Đăng ký học phần");
        btnSVDKHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSVDKHPActionPerformed(evt);
            }
        });

        btnSVKQDKHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSVKQDKHP.setText("Kết quả đăng ký học phần");
        btnSVKQDKHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSVKQDKHPActionPerformed(evt);
            }
        });

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnSVTTTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSVTTTK.setText("Thông tin tài khoản");
        btnSVTTTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSVTTTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(lbSinhVien))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnQuayLai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSVKQDKHP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSVDKHP, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSVTTTK, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addGap(10, 10, 10)
                .addComponent(lbSinhVien)
                .addGap(35, 35, 35)
                .addComponent(btnSVTTTK)
                .addGap(18, 18, 18)
                .addComponent(btnSVDKHP)
                .addGap(18, 18, 18)
                .addComponent(btnSVKQDKHP)
                .addGap(37, 37, 37)
                .addComponent(btnThoat)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnSVTTTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSVTTTKActionPerformed
        new ThongTinTaiKhoan(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSVTTTKActionPerformed

    private void btnSVDKHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSVDKHPActionPerformed
        new DangKyHocPhan(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSVDKHPActionPerformed

    private void btnSVKQDKHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSVKQDKHPActionPerformed
        new KetQuaDangKyHocPhan(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSVKQDKHPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSVDKHP;
    private javax.swing.JButton btnSVKQDKHP;
    private javax.swing.JButton btnSVTTTK;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel lbSinhVien;
    // End of variables declaration//GEN-END:variables
}
