
import dao.MonHocDAO;
import dao.SVDKHPDAO;
import dao.SinhVienDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import pojo.GiaoVien;
import pojo.IDSVDKHP;
import pojo.MonHoc;
import pojo.SVDKHP;
import pojo.SinhVien;
import pojo.TaiKhoan;


public class DanhSachSinhVienDangKyHocPhan extends javax.swing.JFrame {
    TaiKhoan taiKhoan;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form DanhSachSinhVienDangKyHocPhan
     * @param taiKhoan
     */
    public DanhSachSinhVienDangKyHocPhan(TaiKhoan taiKhoan) {
        this.taiKhoan = taiKhoan;
        initComponents();
        
        defaultTableModel = (DefaultTableModel)tbDSSVDKHP.getModel();
        
        themDuLieu();
    }
    
    private void themDuLieu() {
        List<SVDKHP> dsSVDKHP = SVDKHPDAO.layDanhSachSVDKHP();
        for (SVDKHP svdkhp : dsSVDKHP) {
            IDSVDKHP idsvdkhp = svdkhp.getIdSVDKHP();
            SinhVien sv = SinhVienDAO.layThongTinSinhVien(idsvdkhp.getMaSinhVien());
            MonHoc mh = MonHocDAO.layThongTinMonHoc(idsvdkhp.getMaMonHoc());
            GiaoVien gv = svdkhp.getGiaoVien();
            defaultTableModel.addRow(new Object[]{sv.getMaSinhVien(), sv.getTenSinhVien(), 
                mh.getMaMonHoc(), mh.getTenMonHoc(), gv.getTenGiaoVien(), 
                svdkhp.getThoiGianHoc(), svdkhp.getThoiGianDKHP()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuayLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDSSVDKHP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tbDSSVDKHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDSSVDKHP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sinh viên", "Tên sinh viên", "Mã môn học", "Tên môn học", "Tên giáo viên", "Thời gian học", "Thời gian DKHP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDSSVDKHP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbDSSVDKHP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbDSSVDKHP);
        if (tbDSSVDKHP.getColumnModel().getColumnCount() > 0) {
            tbDSSVDKHP.getColumnModel().getColumn(0).setPreferredWidth(70);
            tbDSSVDKHP.getColumnModel().getColumn(1).setPreferredWidth(90);
            tbDSSVDKHP.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbDSSVDKHP.getColumnModel().getColumn(3).setPreferredWidth(250);
            tbDSSVDKHP.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbDSSVDKHP.getColumnModel().getColumn(5).setPreferredWidth(70);
            tbDSSVDKHP.getColumnModel().getColumn(6).setPreferredWidth(70);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuayLai)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        new ChucNangGiaoVu(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDSSVDKHP;
    // End of variables declaration//GEN-END:variables
}
