
import dao.LopHocDAO;
import dao.SinhVienDAO;
import dao.TaiKhoanDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.LopHoc;
import pojo.SinhVien;
import pojo.TaiKhoan;


public class QuanLySinhVien extends javax.swing.JFrame {
    TaiKhoan taiKhoan;
    String tenLop;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form QuanLySinhVien
     * @param taiKhoan
     * @param tenLop
     */
    public QuanLySinhVien(TaiKhoan taiKhoan, String tenLop) {
        this.taiKhoan = taiKhoan;
        this.tenLop = tenLop;
        initComponents();
        
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }        
        };
        
        tbSinhVien.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã sinh viên");
        defaultTableModel.addColumn("Tên sinh viên");
        defaultTableModel.addColumn("Giới tính");
        defaultTableModel.addColumn("Ngày sinh");
        defaultTableModel.addColumn("Tên lớp");
        
        themDuLieu();
    }
    
    private void themDuLieu() {
        List<SinhVien> dssv = SinhVienDAO.layDanhSachSinhVienTrongLop(tenLop);
        
        dssv.forEach(sv -> {
            LopHoc lh = sv.getLop();
            defaultTableModel.addRow(new Object[]{sv.getMaSinhVien(), sv.getTenSinhVien(), 
            sv.getGioiTinh(), sv.getNgaySinh(), lh.getTenLop()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuayLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSinhVien = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnResetMK = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuayLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tbSinhVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSinhVien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbSinhVien);

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnResetMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnResetMK.setText("Reset mật khẩu");
        btnResetMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetMKActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm:");

        txfTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetMK)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuayLai)
                                .addGap(301, 301, 301)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTim)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuayLai)
                    .addComponent(jLabel1)
                    .addComponent(txfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnResetMK)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        new ThemSinhVien(tenLop).setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        new QuanLyLopHoc(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        defaultTableModel.setRowCount(0);
        themDuLieu();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int r = tbSinhVien.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên muốn xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(QuanLySinhVien.this, "Bạn có chắc muốn xóa sinh viên này không?");
            if (confirm == JOptionPane.YES_OPTION) {
                String maSV = (String) tbSinhVien.getValueAt(r, 0);
                SinhVien sv = SinhVienDAO.layThongTinSinhVien(maSV);
                LopHoc lop = LopHocDAO.layThongTinLopHoc(tenLop);
                lop.setTongSinhVien(lop.getTongSinhVien() - 1);
                if ("Nam".equals(sv.getGioiTinh()))
                    lop.setTongNam(lop.getTongNam() - 1);
                else lop.setTongNu(lop.getTongNu() - 1);
                if (SinhVienDAO.xoaSinhVien(maSV)) {
                    TaiKhoanDAO.xoaTaiKhoan(maSV);
                    LopHocDAO.capNhatThongTinLopHoc(lop);
                    JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    defaultTableModel.setRowCount(0);
                    themDuLieu();
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int r = tbSinhVien.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên muốn xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            new CapNhatSinhVien(tenLop, String.valueOf(tbSinhVien.getValueAt(r, 0))).setVisible(true);
            
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnResetMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetMKActionPerformed
        int r = tbSinhVien.getSelectedRow();
        if (r == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên muốn reset mật khẩu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int confirm = JOptionPane.showConfirmDialog(QuanLySinhVien.this, "Bạn có chắc muốn reset mật khẩu không?");
            if (confirm == JOptionPane.YES_OPTION) {
                TaiKhoan tksv = TaiKhoanDAO.layThongTinTaiKhoan(String.valueOf(tbSinhVien.getValueAt(r, 0)));
                tksv.setMatKhau(String.valueOf(tbSinhVien.getValueAt(r, 0)));
                TaiKhoanDAO.capNhatThongTinTaiKhoan(tksv);
                JOptionPane.showMessageDialog(this, "Reset mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnResetMKActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        SinhVien sv = SinhVienDAO.layThongTinSinhVien(txfTimKiem.getText());
        defaultTableModel.setRowCount(0);
        if (sv != null) {
            LopHoc lh = LopHocDAO.layThongTinLopHoc(tenLop);
            defaultTableModel.addRow(new Object[]{sv.getMaSinhVien(), sv.getTenSinhVien(), 
            sv.getGioiTinh(), sv.getNgaySinh(), lh.getTenLop()});
        }
        
    }//GEN-LAST:event_btnTimActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnResetMK;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbSinhVien;
    private javax.swing.JTextField txfTimKiem;
    // End of variables declaration//GEN-END:variables
}
