
import dao.HocKiDAO;
import dao.HocPhanDAO;
import dao.KiDKHPDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.HocKi;
import pojo.IDHocKi;
import pojo.KiDKHP;
import pojo.TaiKhoan;

public class QuanLyKiDKHP extends javax.swing.JFrame {
    TaiKhoan taiKhoan;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form QuanLyKiDKHP
     * @param taiKhoan
     */
    public QuanLyKiDKHP(TaiKhoan taiKhoan) {
        this.taiKhoan = taiKhoan;
        initComponents();
        defaultTableModel = (DefaultTableModel)tbKiDKHP.getModel();
        
        themDuLieu();
    }
    
    private void themDuLieu() {
        List<KiDKHP> dskiDKHP = KiDKHPDAO.layDanhSachKiDKHP();
        
        dskiDKHP.forEach(ki -> {
            IDHocKi idhk = ki.getIdHocKi();
            defaultTableModel.addRow(new Object[]{idhk.getTenHocKi(), 
                idhk.getNamHoc(), ki.getNgayBD(), ki.getNgayKT()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQuayLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKiDKHP = new javax.swing.JTable();
        btnTao = new javax.swing.JButton();
        btnHocPhan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        tbKiDKHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbKiDKHP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Học kì", "Năm học", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKiDKHP.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbKiDKHP.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbKiDKHP);
        if (tbKiDKHP.getColumnModel().getColumnCount() > 0) {
            tbKiDKHP.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbKiDKHP.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbKiDKHP.getColumnModel().getColumn(2).setPreferredWidth(120);
            tbKiDKHP.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        btnTao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTao.setText("Tạo kì đăng ký học phần");
        btnTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoActionPerformed(evt);
            }
        });

        btnHocPhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHocPhan.setText("Tạo học phần");
        btnHocPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocPhanActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Làm mới");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuayLai)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTao)
                        .addGap(18, 18, 18)
                        .addComponent(btnHocPhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTao)
                    .addComponent(btnHocPhan)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        new ChucNangGiaoVu(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoActionPerformed
        List<HocKi> dshk = HocKiDAO.layThongTinHocKiHienTai();
        HocKi hk = dshk.get(0);
        IDHocKi idhk = hk.getIdHocKi();
        if (KiDKHPDAO.layThongTinKiDKHP(idhk) == null) {
            HocPhanDAO.xoaTatCaHocPhan();
            new TaoKiDKHP(idhk).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Kì đăng ký học phần của học kì hiện tại đã có", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTaoActionPerformed

    private void btnHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocPhanActionPerformed
        new DanhSachHocPhan(taiKhoan).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHocPhanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHocPhan;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTao;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbKiDKHP;
    // End of variables declaration//GEN-END:variables
}
